# The most funcamental concepts of tensors using TensorFlow


## Introduction to Tensors

In [29]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [30]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [31]:
# Check the number of dimensions of a tensor (ndim--number of the dimension)
scalar.ndim

0

In [32]:
from numpy.lib.function_base import vectorize
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [33]:
# Check the dimension of a vector
vector.ndim

1

In [34]:
# Matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [35]:
matrix.ndim

2

In [36]:
# Create another matrix and specify dtype
matrix_b = tf.constant([[10.,7],[9.,10],[8.,9.]], dtype=tf.float16)
matrix_b

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 9., 10.],
       [ 8.,  9.]], dtype=float16)>

In [37]:
matrix_b.ndim

2

In [38]:
matrix_c = tf.constant([[[2,1,3],[2,3,1]],[[12,2,3],[9,2,10]]])
matrix_c

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 2,  1,  3],
        [ 2,  3,  1]],

       [[12,  2,  3],
        [ 9,  2, 10]]], dtype=int32)>

In [39]:
matrix_c.ndim

3

To conclude what we've done so far.
* Scalar: a single number
* Vector: a number with direction.
* Matrix: a 2-dimensional array
* Tensor: an n-dimensional array of numbers.

### CREATE tensors with `tf.Variables`

In [40]:
# Create the same tensor as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor= tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [41]:
# If we try to change one of the elements in the changeable tensor
# changeable_tensor[0] = 7
# changeable_tensor

In [42]:
# change with .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [43]:
# Try change the unchangeable one
# unchangeable_tensor[0].assign(7)
# unchangeable_tensor

### Create random tensors

Random tensors are tensors of some arbitrary numbers.

In [44]:
from tensorflow._api.v2 import random
# Create two random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1,random_2

# Are the equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in tensor

In [45]:
# Shuffle a tensor (valuable for when you wnat to shuffle your data so the inhenrent order doesn't effect learning)
not_shuffled = tf.constant([[19,7],[3,4],[2,10]])
not_shuffled.ndim

2

In [46]:
# Shuffle the not_shuffled tensor
tf.random.set_seed=42
tf.random.shuffle(not_shuffled, seed=42)

#If the operation seed is set, but the global seed is not set:
# A default global seed and the specified operation seed are used to determine the random sequence.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 3,  4],
       [19,  7]], dtype=int32)>

**Exercise:** Read through TensorFlow documentation on random seed. And writing 5 random cases and shuffle them.

> Rule 4:If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [47]:
# If I use tf.constant to test the shuffle when global seed and operation seed are set together
# tf.random.set_seed
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 3,  4],
       [19,  7]], dtype=int32)>

### Other ways to make tensors

In [48]:
# Create a tensor all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [49]:
# Create a tensor all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

Tensors cna be run on a GPU (much faster for numeric computing)

In [50]:
# Turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A
# x = tf.constant()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [51]:
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape=(2,3,4))
A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Getting information from tensors

* Shape (number of elements)-- tensor.shape
* Rank (number of tensor dimensions)-- tensor.ndim
* Axis or dimension (particular dimension) -- tensor[0]
* Size (total number of items)-- tf.size(tensor)



In [52]:
# Create a rank for tensor (4 dimension)

rank_4_tensor = tf.zeros([3,3,3,3])
rank_4_tensor

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [53]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([3, 3, 3, 3]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=81>)

In [54]:
# Get various attribute of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in a tensor:", tf.size(rank_4_tensor))
print("Total number of elements in a tensor in numpy:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 3, 3, 3)
Elements along the 0 axis: 3
Elements along the last axis: 3
Total number of elements in a tensor: tf.Tensor(81, shape=(), dtype=int32)
Total number of elements in a tensor in numpy: 81


### Indexing tensors
Tensors can be indexed just like Python lists.

In [55]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [56]:
rank_4_tensor[:-1,:,:]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [57]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [58]:
from tensorflow.python.ops.gen_array_ops import rank
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],[2,8]])#tf.zeros(shape=(2,2))
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [59]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>

In [60]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_2_tensor,rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 2],
         [ 8]]], dtype=int32)>)

In [61]:
#Alternative to tf.newaxise->expand_dims(input, axis)
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 2],
        [ 8]]], dtype=int32)>

In [62]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis
# same as
# rank_2_tensor[tf.newaxis,...]

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 2,  8]]], dtype=int32)>

### Manipulating tensors

**Basic operations**

`+`,`-`,`*`,`/`

In [63]:
# add values using addtion operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [64]:
# Original tensor is unchanged
tensor
# To change it, use assignment `=`

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [65]:
# Multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [66]:
# subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [67]:
# Divsion
tensor/10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [68]:
# We can use the tensorflow built-in function too
# The original one is still unchanged
# If you want to speed up, use tf.operation to mulipuate your tensor
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [69]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [70]:
# Matrix mulitiplication in TensorFlow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [71]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [72]:
tensor1 = tf.constant([[[1,2,5],[7,2,1],[3,3,3]]])
tensor2 = tf.constant([[[3,5],[6,7],[1,8]]])
tensor1, tensor2

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 5],
         [7, 2, 1],
         [3, 3, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[3, 5],
         [6, 7],
         [1, 8]]], dtype=int32)>)

In [73]:
# Testing matmul using tensor1 and tensor2
tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [74]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [75]:
# Create two shape(3,2) tensors
X = tf.constant([[1,2],[3,4],[5,6]])
Y = tf.constant([[1,2],[3,4],[5,6]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [76]:
# Multiply them.
# wrong way: tf.matmul(X,Y), because their inner dimension does not match
tf.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [77]:
# If we reshape X to (2,3), the shape of the result of mutiplication is (2,2)
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [78]:
# Use transpose
# perm represent the dimension of original matrix that new matrix to be
# e.g if the first dimension is unchanged, then the first value of perm is 0 (per=[0....])
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [79]:
# Transpose practice
Z = tf.constant([[[1,2],[3,4],[5,6]]])
Z, tf.transpose(Z, perm=[0,2,1])

(<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4],
         [5, 6]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
 array([[[1, 3, 5],
         [2, 4, 6]]], dtype=int32)>)

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multi using:
* `tf.matmul()`
* `tf.tensordot()`

In [80]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

In [81]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

In [82]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y,(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [83]:
# Y, reshaped Y and transposed Y
print(Y,"\n")

print(tf.reshape(Y, (2,3)),"\n")
print(tf.transpose(Y),"\n")

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32) 



### Changing the datatype of a tensor

In [84]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [85]:
C =  tf.constant([1,7])
C.dtype

tf.int32

In [86]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [87]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [88]:
E_float16 = tf.cast(E, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 7.], dtype=float16)>

### Aggregating tensors
Aggregating: condensing them from multiple values down to a smaller amount of values.

In [90]:
# Get the absolute values
D = tf.constant([-7,-10])
absolute_D = tf.abs(D)
D, absolute_D

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Various forms of aggregation:
* minimum
* maximum
* mean
* sum

In [91]:
# Create a random tensor with values between 0 and 100 with a size of 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([46, 48, 10, 19, 53, 45, 11, 67, 22, 89, 20,  6, 59, 67, 65, 56, 43,
       91, 52, 87, 45, 94, 30, 12, 26,  7, 42, 83, 61, 32, 27, 10, 74, 65,
       19, 35, 57, 30, 28, 84, 13, 27, 14, 59,  5,  5, 32, 98, 54, 39])>

In [92]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [93]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [94]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [95]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [96]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2163>

**Exercise:** find the variance and standard deviation

In [99]:
# variance
E_float32 = tf.cast(E, dtype=tf.float32)
tf.math.reduce_variance(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=703.0324>

In [101]:
# standard deviation
tf.math.reduce_std(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=26.51476>

In [102]:
# another method to get var. and std.
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=703>

In [104]:
tfp.stats.stddev(E_float32)

<tf.Tensor: shape=(), dtype=float32, numpy=26.51476>

### Find the positional maximum and minimum

In [106]:
# Create a new tensor
tf.random.set_seed=42
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.1329987 , 0.07000387, 0.589828  , 0.49349093, 0.8226495 ,
       0.57330346, 0.8306253 , 0.90651655, 0.6321647 , 0.9903176 ,
       0.20048988, 0.66986954, 0.03981864, 0.20150054, 0.00759172,
       0.75790715, 0.37229872, 0.824312  , 0.9726354 , 0.23151135,
       0.7225182 , 0.31309152, 0.50887907, 0.9464282 , 0.08523715,
       0.8897158 , 0.07869458, 0.45036864, 0.9532627 , 0.20423138,
       0.19134152, 0.89875937, 0.07065761, 0.46080887, 0.82636034,
       0.5638882 , 0.38303423, 0.3173715 , 0.03328216, 0.82079744,
       0.57467747, 0.13530314, 0.49956882, 0.17566586, 0.45082772,
       0.47622013, 0.782848  , 0.70693636, 0.84061456, 0.69389546],
      dtype=float32)>

In [109]:
# Find the positional maximum
tf.argmax(F), F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=9>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9903176>)

In [111]:
# Find the positional minimum
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=14>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0075917244>)

### Squeezing a tensor (removing all single dimensions)

In [114]:
# Create a tensor with single dimensions
tf.random.set_seed=42
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.8309741 , 0.26148272, 0.6798481 , 0.9094031 , 0.6389327 ,
          0.7323853 , 0.7365134 , 0.24626815, 0.41289186, 0.33605933,
          0.28829014, 0.32565093, 0.12410331, 0.2774936 , 0.45209718,
          0.22422636, 0.14978027, 0.7111434 , 0.00412261, 0.05469608,
          0.174461  , 0.32096517, 0.11514533, 0.7496952 , 0.90726256,
          0.4104874 , 0.3774836 , 0.7505609 , 0.24945664, 0.24593735,
          0.64847684, 0.4677856 , 0.8432561 , 0.7061486 , 0.8830948 ,
          0.16012084, 0.76339865, 0.11461711, 0.30767572, 0.16761208,
          0.5087236 , 0.45787454, 0.13303173, 0.25298572, 0.3753848 ,
          0.3527453 , 0.99135983, 0.69654405, 0.44039416, 0.01904571]]]],
      dtype=float32)>

In [115]:
G.shape

TensorShape([1, 1, 1, 50])

In [116]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.8309741 , 0.26148272, 0.6798481 , 0.9094031 , 0.6389327 ,
        0.7323853 , 0.7365134 , 0.24626815, 0.41289186, 0.33605933,
        0.28829014, 0.32565093, 0.12410331, 0.2774936 , 0.45209718,
        0.22422636, 0.14978027, 0.7111434 , 0.00412261, 0.05469608,
        0.174461  , 0.32096517, 0.11514533, 0.7496952 , 0.90726256,
        0.4104874 , 0.3774836 , 0.7505609 , 0.24945664, 0.24593735,
        0.64847684, 0.4677856 , 0.8432561 , 0.7061486 , 0.8830948 ,
        0.16012084, 0.76339865, 0.11461711, 0.30767572, 0.16761208,
        0.5087236 , 0.45787454, 0.13303173, 0.25298572, 0.3753848 ,
        0.3527453 , 0.99135983, 0.69654405, 0.44039416, 0.01904571],
       dtype=float32)>,
 TensorShape([50]))

### One-hot Encoding tensors

In [117]:
# Create a list of indices
some_list = [0,1,2,3]

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [119]:
# Create a categorical list => won't work
# cat_list = ['blue', 'red', 'yellow', 'black']
# tf.one_hot(cat_list, depth=4)

In [120]:
# Specify cunstom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

### Squaring, log, squre root

In [121]:
# New tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [122]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [125]:
# Squre root (method require non-int type)
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [128]:
# find the log (method require non-int type)
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow intracts beautifully with Numpy arrays.

**Note:** Main difference between Numpy and TensorFlow is that tensorflow can be run on a GPU or TPU (for faster numeric processing)

In [130]:
# New tensor
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [131]:
# Convert tensor to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [133]:
# Convert tensor J to a Numpy array
J.numpy(), J.numpy()[0]

(array([ 3.,  7., 10.]), 3.0)

In [134]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
# check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Try to find access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Tue Jun 27 15:06:43 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    13W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

>**Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.